### ISSUE TITLE
block_scan.cuh missing

### ISSUE THREAD

**Issue by curtpm** [NVlabs/cub#100]
```
build/third_party/src/CUBExternal/cub/block/block_radix_rank.cuh:38:35: fatal error: ../block/block_scan.cuh: No such file or directory
 #include "../block/block_scan.cuh"
```

it looks like somehow the commit ref was purged from the repo:
https://github.com/NVlabs/cub/tree/1.7.0/cub/block

its been renamed by git to "block_scan.cuh.REMOVED.git-id" and references the old hash it use to be

**Comment by dumerrill** [comment]
Just replaced it, thanks for noticing!

(In an effort to drastically reduce the clone size from 130+MB, we recently purged the repo of non-HEAD files over 100KB -- primarily binaries and test input data that had since been removed.  In an oversight, we neglected to protect the non-HEAD refs, so block_scan.cuh was purged in all branches but master.  I've replaced it in each branch with it's appropriate version.)
