### ISSUE TITLE
GitHub release or another way to reproducibly get binary

### ISSUE THREAD

**Issue by lostmsu** [NVlabs/cub#101]
Hey guys,
I am working with TensorFlow, and just noticed, that Windows build fails due to file hash mismatch.
Apparently, it downloads cub from https://github.com/NVlabs/cub/archive/1.6.4.zip , and this file seems to be changing over time.

Is there a url for unchanging binary? Like a GitHub release, or maybe something internal, which TF build could use.

**Comment by ebrevdo** [comment]
+1 this makes it hard for TensorFlow to include CUB releases.  Can you keep the release files immutable?

**Comment by ebrevdo** [comment]
@lostmsu if you're still experiencing this bug please cross-post to tensorflow issues and we'll update the hash.

**Comment by dumerrill** [comment]
Yep, as mentioned in https://github.com/NVlabs/cub/issues/77, we'll be using GIT tags moving forward to demarcate immutable releases (as well as keeping the last major.minor.last branches for customer hotfixes).  The breaking of hashes was a one-time necessity to address https://github.com/NVlabs/cub/issues/94 (purge orphan bloat from the repository because of unreasonable git history size.)
