### ISSUE TITLE
Initial value assignments in block_scan.cuh

### ISSUE THREAD

**Issue by brycelelbach** [NVlabs/cub#113]
Hey Duane,

In block_scan.cuh, the following four overloads of `ExclusiveSum` (all of which use `operator+` as the scan operation instead of a user-provided operation) create and zero-assign a `T` and pass it as the initial value argument to `ExclusiveScan` (`ExclusiveSum` is implemented via `ExclusiveScan` - it's just a forwarding function to it):

* https://github.com/NVlabs/cub/blob/1.7.3/cub/block/block_scan.cuh#L337 (T/T& arguments, no operator provided, no initial value provided, no block aggregate parameter). 
* https://github.com/NVlabs/cub/blob/1.7.3/cub/block/block_scan.cuh#L385 (T/T& arguments, no operator provided, no initial value provided, block aggregate parameter).
* https://github.com/NVlabs/cub/blob/1.7.3/cub/block/block_scan.cuh#L525 (reference to array of T arguments, no operator provided, no initial value provided, no block aggregate parameter).
* https://github.com/NVlabs/cub/blob/1.7.3/cub/block/block_scan.cuh#L578 (reference to array of T arguments, no operator provided, no initial value provided, block aggregate parameter).

This introduces a requirement that the type `T` be assignable from the literal `0`.

However, the following four overloads of `ExclusiveSum` (all of which use a user-provided operation as the scan operation) do NOT create and zero-assign a `T`:

* https://github.com/NVlabs/cub/blob/1.7.3/cub/block/block_scan.cuh#L470 (T/T& arguments, user-defined operator provided, no initial value provided).
* https://github.com/NVlabs/cub/blob/1.7.3/cub/block/block_scan.cuh#L678 (reference to array of T arguments, user-defined operator provided, no initial value provided).

There does appear to be suitable overloads of `ExclusiveScan` which do not take initial value arguments; it's not clear to me why the first four `ExclusiveSum`s create an initial value and pass it to `ExclusiveScan` instead of calling one of these (respectively):

* https://github.com/NVlabs/cub/blob/1.7.3/cub/block/block_scan.cuh#L1141
* https://github.com/NVlabs/cub/blob/1.7.3/cub/block/block_scan.cuh#L1162
* https://github.com/NVlabs/cub/blob/1.7.3/cub/block/block_scan.cuh#L1192
* https://github.com/NVlabs/cub/blob/1.7.3/cub/block/block_scan.cuh#L1224

I haven't had a chance to test switching to those overloads yet, or dig into the code enough to be certain it'd be the right thing to do.

**Comment by dumerrill** [comment]
> This introduces a requirement that the type T be assignable from the literal 0.

Yes, but only for the _*Sum_ versions, which also imply "plus" as the associative operator. (Note that these are precisely the same semantics as Thrust [exclusive_scan ](https://thrust.github.io/doc/group__prefixsums.html#ga333bd4f34742dcf68d3ac5a0933f67db) variants that do not take an init value or scan operator)

> However, the following four overloads of ExclusiveSum (all of which use a user-provided operation as the scan operation) do NOT create and zero-assign a T

If you look closely, those variants take a functor that provides the initial value, so there is no need to assign from 0.

The four variants of ExclusiveScan you list at the end are not part of the official API; because they do not take initial value argument (and none is implied), their semantics are quirkly.  As described in the doxygen: "With no initial value, the output computed for <em>thread</em><sub>0</sub> is undefined"
