### ISSUE TITLE
cub::DeviceRadixSort::SortPairs not working properly 

### ISSUE THREAD

**Issue by GMolini** [NVlabs/cub#116]
I have noticed that, from a certain number (dependent on the GPU) the SortPairs algorithm stops working.

Here is the code I have used for proving it:
```
#include <stdio.h>
#include<vector>
#include<iostream>
#include<cuda_runtime.h>
#include <thrust/sort.h>
#include <thrust/functional.h>
#include <thrust/execution_policy.h>
#include <thrust/sequence.h>
#include <cub/cub.cuh>
#include <thrust/device_vector.h>


int main()
{

 cudaDeviceReset();
 cudaSetDevice(1);

  int n_elems = 256*1024;


  std::vector<int> keys(n_elems);
  std::vector<int> values (n_elems);

  for(int i=0;i<n_elems;i++)
  {
    keys[i] = rand() % 100000;
    values[i] = i;
  }

  thrust::device_vector<int> t_keys = keys;
  thrust::device_vector<int> t_values = values;

  thrust::sort_by_key(thrust::device,
                      t_keys.begin(),
                      t_keys.end(),
                      t_values.begin(),
                      thrust::less<int>());



  int *d_keys;
  int *d_values;

 cudaMalloc((void**) &d_keys, n_elems * sizeof(int));
 cudaMalloc((void**) &d_values, n_elems * sizeof(int));

 cudaMemcpy(d_keys, keys.data(), n_elems * sizeof(int), cudaMemcpyHostToDevice);
 cudaMemcpy(d_values, values.data(), n_elems * sizeof(int), cudaMemcpyHostToDevice);

 void *dtemp = NULL;
 size_t expected_size = 0;
 cub::DeviceRadixSort::SortPairs(
                       dtemp,
                       expected_size,
                       d_keys,
                       d_keys,
                       d_values,
                       d_values,
                       n_elems,
                       0,
                       32,
                       0,
                       true);

 std::cout << "Temp size " << expected_size << std::endl;
 cudaMalloc((void**) &dtemp, expected_size );

cudaGetLastError();
 cub::DeviceRadixSort::SortPairs(
                       dtemp,
                       expected_size, //size,
                       d_keys,
                       d_keys,
                       d_values,
                       d_values,
                       n_elems,
                       0,
                       32,
                       0,
                       true);
cudaDeviceSynchronize();
cudaGetLastError();

  std::vector<int> cub_keys_output(n_elems);
  std::vector<int> cub_values_output(n_elems);

 cudaMemcpy(cub_keys_output.data(), d_keys, n_elems * sizeof(int), cudaMemcpyDeviceToHost);
 cudaMemcpy(cub_values_output.data(), d_values, n_elems * sizeof(int), cudaMemcpyDeviceToHost);


 int diff_count = 0;
 for(int i=0;i<n_elems;i++)
 {
   if(cub_keys_output[i] != t_keys[i]) diff_count++;
    //std::cout << "Sorted differently!!! cub: " << cub_keys_output[i] << " thrust:" << t_keys[i] << "\n";
 }
 if(0 == diff_count)std::cout << "Sorted the same!!!  " << diff_count << " diferences"<< std::endl;
 else std::cout << "Sorted differently!!!  " << diff_count << " difefrences"<< std::endl;

 cudaFree(d_keys);
 cudaFree(d_values);
 cudaFree(dtemp);
    return 0;
}
```

Using this code, if i run it on the Titan XP, there is no problem and the algorithm returns the values as expected. If I run it on a 1070, it doesnt sort the keys correctly. From a certain number, it stops working on the XP too (1024 * 1024 for example doesnt work).
The number of elements that provoke the mistake seems to be related to the number of SMs.

**Comment by dumerrill** [comment]
You can't alias the output arrays to the input arrays.  (The documentation isn't clear on this, and I apologize.  We'll add that feature shortly.)  If you have separate output arrays, then it works fine.

**Comment by GMolini** [comment]
Ah ok. I thought you could do an in place sort. Thanks!

**Comment by dumerrill** [comment]
Yeah, there are tradeoffs, mostly relating to scratch storage and copying.

The radix sorting method works by iterating digit-binning passes over the keys.  They keys (and values) need to ping-pong between two different buffers as they are repeatedly re-binned.  The number of passes depends on how many bits per digit, and the the optimal digit width is different from one architecture to the next.  (Newer architectures that provision more register file and scratch memory are typically more efficient with wider digits and thus fewer passes.)  

- If you have separate input and output arrays, you'll need an extra array as temporary storage if there is an even number of passes needed to cover the desired range of distinguishing bits.  Storage is 3N: (input, output, temp).

- If you have aliased input and output arrays, you'll need two extra arrays as temporary storage if there is an odd number of passes needed to cover the desired range of distinguishing bits.  Storage is 3N: input, temp1, temp2.  We haven't implemented this because, well, nobody's really asked for it.

- If you don't care if your input is destroyed and don't mind letting CUB tell you where the sorted array is, you can provide your own double-buffer (with "active" selector) and the storage is 2N: ping, pong.
