### ISSUE TITLE
Block reduce with diffirent ops

### ISSUE THREAD

**Issue by hiyijian** [NVlabs/cub#84]
hi stuff,
   I am working on 2D matrix reduce with "sum" and "max" operation. Specifically, I want to reduce M * N matrix to M vector, in which the element is sum or max value per row

   While "sum" works perfect with following codes, the "max" failed when compile
```
template <typename Dtype>
__global__  void caffe_gpu_rmax(const int n, const int n_row,
      const Dtype * indata, Dtype * outdata) {
    unsigned int tid = blockIdx.x * blockDim.x + threadIdx.x;
    typedef cub::BlockReduce<Dtype, M> BlockReduceT;  // line label A
    __shared__ typename BlockReduceT::TempStorage temp_storage;
    Dtype result;
    if(tid < n) result = BlockReduceT(temp_storage).Sum(indata[tid]);     // line label B
    if(threadIdx.x == 0) outdata[blockIdx.x] = result;
}
// call
caffe_gpu_sum<Dtype><<<N, M>>>(M*N, M, in_data, out_data);
```
I have two question about this:
- See line label A. M must be a constant so that compiler is aware of its value. This limitation prevents me to reduce a matrix with dynamic number of rows.  Is there a way to make it?
- See line lable b. I tried to change "Sum" to "Max", but failed.  Is there a way to make it?

Thanks

**Comment by dumerrill** [comment]
A couple things: 

Thing 1: Because `BlockReduce `is a block-wide collective, you need to have *all* threads in the CTA invoke it; you have it guarded in a way that seems like that requirement won't necessarily be met.  (I'm surprised it didn't hang on you because there's a `syncthreads`() inside.)  You might try something like:

```
Dtype datum = (tid < n) ? indata[tid] : 0;
Dtype result = BlockReduceT(temp_storage).Sum(datum);
```

That way all threads participate.  

Thing 2: Are you assigning one CTA per row?  (It's not clear that's what you're doing from this snippet, but that would be what makes sense from the fact that you're doing a cooperative reduction across CTA threads). You can then use the the CTA to reduce arbitrary-length rows by an extension of the following:

```
...
int row_id = blockIdx.x;
if (row_id < n_row)
{
    int row_offset = ...[row_id];
    int row_length = ...[row_id + 1] - row_offset;
    Dtype thread_partial = 0;
    for (int i = threadIdx.x; i < row_length; i += BLOCK_THEADS) 
        thread_partial += in_data[row_offset + i];

    Dtype result = BlockReduceT(temp_storage).Sum(thread_partial );
}
...
```

**Comment by dumerrill** [comment]
Closing for lack-of-followup.
