### ISSUE TITLE
Incorrect results with ReduceByKey

### ISSUE THREAD

**Issue by samuelpmish** [NVlabs/cub#86]
I'm seeing some incorrect results when using CUB's DeviceReduce::ReduceByKey. However, using the same inputs/outputs with thrust::reduce_by_key produces the expected answers:

https://pastebin.com/818ZJFbV

it seems to be sensitive to the -gencode compile flag too (sm_35 for the GTX Titan workstation). Leaving these flags out makes it work again.

$ nvcc tmp.cu -gencode arch=compute_35,code=sm_35
$ ./a.out 
CUB
0, 4000
1, 1000
2, 768

thrust
0, 4000
1, 1000
2, 2680
$ nvcc tmp.cu
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning)
$ ./a.out 
CUB
0, 4000
1, 1000
2, 2680

thrust
0, 4000
1, 1000
2, 2680

Tried on two separate machines with cuda 8, ubuntu 16.04, cub 1.6.4, gcc 5.4.0. One machine has a GTX Titan (cc 3.5), and the other machine has a GTX 1080 Ti (cc 6.1).

**Comment by dumerrill** [comment]
Hi, what version of CUB and the Toolkit are you using?


On Wed, Apr 5, 2017 at 2:52 PM samuelpmish <notifications@github.com> wrote:

I'm seeing some incorrect results when using CUB's
DeviceReduce::ReduceByKey. However, using the same inputs/outputs with
thrust::reduce_by_key produces the expected answers:

https://pastebin.com/818ZJFbV

it seems to be sensitive to the -gencode compile flag too (sm_35 for the
GTX Titan workstation). Leaving
out these flags makes it work again.

$ nvcc tmp.cu -gencode arch=compute_35,code=sm_35
$ ./a.out
CUB
0, 4000
1, 1000
2, 768

thrust
0, 4000
1, 1000
2, 2680
$ nvcc tmp.cu
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are
deprecated, and may be removed in a future release (Use
-Wno-deprecated-gpu-targets to suppress warning)
$ ./a.out
CUB
0, 4000
1, 1000
2, 2680

thrust
0, 4000
1, 1000
2, 2680

Tried on two separate machines with cuda 8, ubuntu 16.04, cub 1.6.4, gcc
5.4.0. One machine has a GTX Titan (cc 3.5), and the other machine has a
GTX 1080 Ti (cc 6.1).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NVlabs/cub/issues/86>, or mute the thread

**Comment by samuelpmish** [comment]
Cuda 8 and cub 1.6.4

**Comment by dumerrill** [comment]
You're right, it's a bug.  Fix is in for the next CUB release scheduled for next week (GTC & CUDA 9.0).

**Comment by dumerrill** [comment]
Fixed in commit 521ad225c5ff720473208b5c31d50ae10d2c8e1d

**Comment by samuelpmish** [comment]
Thanks for the quick turnaround-- love this library, it sped up my research codes by a factor of 4-5x!
